### ISSUE TITLE
Refactor: 폴더 구조, 명칭 리펙토링 제안

### ISSUE THREAD

**Issue by sjsjsj1246** [Hipspot/hipspot-web#24]
## Description

폴더 네이밍 규칙 통일 및 alias 적용

## Todo

- [ ] src/api -> src/libs/apis
- [ ] src/container -> src/containers
- [ ] alias에 containers 추가

**Comment by Sangjun-man** [comment]
저도 제안 하나 하고싶은데
@recoil -> @states 로 명칭을 변경했으면 좋겠어요
@recoil 안의 값들이 상태이기도 하고, 임포트 할 때 리코일 내장 함수랑 많이 헷갈리는것 같습니다 
예를들어
``` javascript
import {useRecoilState} from 'recoil'
import {markerState} from '@recoil' 
```
이런식의 경우에도 헷갈리는것 같습니다~
