### ISSUE TITLE
Feat: 인포윈도우 상태관리

### ISSUE THREAD

**Issue by hyorish03** [Hipspot/hipspot-web#26]
## Description

- 인포윈도우 상태 관리

## Todo

- [x] 마커 클릭 시 활성화 아이디 저장
- [x] 활성화된 카페 아이디가 있을 경우 바 표시
- [x] 활성화된 카페 아이디를 기준으로 서버에서 카페 정보 가져옴
- [ ] 주소 복사 버튼 구현
- [x] 네이버 카카오 지도 버튼 구현

## References

- activatedIdAtom
- [SelectorFamily](https://recoiljs.org/ko/docs/api-reference/utils/selectorFamily/) 사용하여 카페 정보 유지
