### ISSUE TITLE
Feat : PopUpWindow 플리킹 기능 구현

### ISSUE THREAD

**Issue by Sangjun-man** [Hipspot/hipspot-web#77]
## Description

- 화면 하단에서 위로 플리킹하는 제스쳐를 인식해서, 인포윈도우를 최상단 또는 최하단으로 내리는 기능을 구현합니다

## Todo

- [x] 이벤트 인식 범위와 정확한 타겟 지정을 위한 컴포넌트 구조 수정
- [x] 이벤트 인식 위치 지정
- [x] 플리킹 기능 구현
- [x] 느린 속도에도 플리킹 되는 버그 수정
- [x] 터치시 스크롤 되는 버그 수정
## References

- 플리킹 모션 참고 : https://webclub.tistory.com/416
